{{- $GitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- $labels := include "base-chart.labels" . }}
{{- $fullName := include "base-chart.fullname" . -}}
{{- range .Values.ingresses }}
{{- if not .disabled -}}
{{- if semverCompare ">=1.14-0" $GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .tls }}
  tls:
  {{- range .tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .rules }}
    - http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .servicePort }}
    {{- if .host }}
      host: {{ .host | quote }}
    {{- end}}
  {{- end }}
---
{{- end -}}
{{- end }}
