{{- $GitVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $labels := include "base-chart.labels" . -}}
{{- $fullName := include "base-chart.fullname" . -}}
{{- range .Values.ingresses }}
{{- if not .disabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .spec.ingressClassName }}
  ingressClassName: {{ .spec.ingressClassName }}
  {{- end }}
{{- if .spec.tls }}
  tls:
  {{- range .spec.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if .spec.rules }}
  rules:
  {{- range .spec.rules }}
    - http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName | default $fullName }}
                port: 
                  number: {{ .servicePort }}
    {{- if .host }}
      host: {{ .host | quote }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
