apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "containers-pod.fullname" . }}
  labels:
    {{- include "containers-pod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pod.replicaCount }}
  selector:
    matchLabels:
      {{- include "containers-pod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "containers-pod.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "containers-pod.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pod.podSecurityContext | nindent 8 }}
      {{- if .Values.pod.volumes }}
      volumes:
        {{- toYaml .Values.pod.volumes | nindent 8 }}
      {{- end }}
      {{- include "mapper.containers" . | nindent 6 }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
